### ISSUE TITLE
[Future] 文字发送至游戏内异常时提供合适的报错信息

### ISSUE THREAD

**Issue by IceBlues** [uiharuayako/SpeakBeaver#2]
正确配置后观察后台日志, 可以正确进行语音识别, 但语音识别后的结果无法正常发送到游戏内, 报错: websocket send error: Connection is already closed.

游戏内聊天栏, 鲇鱼精邮差日志, console log如下:

![QQ图片20230318212625](https://user-images.githubusercontent.com/24807179/226109090-acf87b0b-c3c8-4d98-bbd9-1f0625c71c43.png)
![Snipaste_2023-03-18_21-26-43](https://user-images.githubusercontent.com/24807179/226109099-eab83498-fe69-4fc2-9cab-77230110c87e.png)
![Snipaste_2023-03-18_21-26-52](https://user-images.githubusercontent.com/24807179/226109105-c0e123bf-6bd9-47d7-8664-e0f682fd2e97.png)

之后进行了多次尝试, 发现只是因为没有组成小队所以无法正常发送到小队列表, 建议在后台日志能够给出更清楚的错误提示

**Comment by uiharuayako** [comment]
他这个报错其实是正常的，你现在是小队频道，如果没有小队鲶鱼精应该不会发，试试说话频道有没有问题

**Comment by IceBlues** [comment]
> 他这个报错其实是正常的，你现在是小队频道，如果没有小队鲶鱼精应该不会发，试试说话频道有没有问题

是这样的, 之后我又进行了几次尝试发现只是因为没有组成小队所以无法正确发送, 如果针对后台的报错日志能有更详细的提示就好了, 感谢回复!

**Comment by uiharuayako** [comment]
我看了一下鲶鱼精的返回值，以http形式调用接口，不管是否成功发到游戏，返回的信息都是ok（代码200），body为消息的内容，单这样看不出发送的成功与否，如果鲶鱼精那边之后的更新加了返回发送情况的功能，我会考虑跟进
